apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dagster
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: dagster-values
    files:
      - dagster_values.yaml=../../../app/dev/dagster_values.yaml
configurations:
  - kustomizeconfig.yaml